# Generated by Django 3.2.5 on 2021-08-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(verbose_name='Serhinizi bildirin'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_author',
            field=models.EmailField(max_length=254, verbose_name='Emailinizi yazin'),
        ),
    ]
